-- Creating Required DB's, Schema's 

CREATE DATABASE EDW_PRODUCTION_DB;
USE DATABASE EDW_PRODUCTION_DB;
  CREATE SCHEMA EDW_PROD_LANDING_SC;
  CREATE SCHEMA EDW_PROD_BRONZE_SC;
  CREATE SCHEMA EDW_PROD_SILVER_SC;
  CREATE SCHEMA EDW_PROD_GOLD_SC;
  CREATE SCHEMA EDW_PROD_PROCESS_SC;

CREATE DATABASE EDW_DEVELOPMENT_DB;
USE DATABASE EDW_DEVELOPMENT_DB;
  CREATE SCHEMA EDW_DEV_LANDING_SC;
  CREATE SCHEMA EDW_DEV_BRONZE_SC;
  CREATE SCHEMA EDW_DEV_SILVER_SC;
  CREATE SCHEMA EDW_DEV_GOLD_SC;
  CREATE SCHEMA EDW_DEV_PROCESS_SC;


CREATE DATABASE EDW_QUALITY_ANALYSIS_DB;
USE DATABASE EDW_QUALITY_ANALYSIS_DB;
  CREATE SCHEMA EDW_QA_LANDING_SC;
  CREATE SCHEMA EDW_QA_BRONZE_SC;
  CREATE SCHEMA EDW_QA_SILVER_SC;
  CREATE SCHEMA EDW_QA_GOLD_SC;
  CREATE SCHEMA EDW_QA_PROCESS_SC;