-- Creating Required DB's, Schema's & Warehouse's.
USE DATABASE EDW_PRODUCTION_DB;
CREATE DATABASE EDW_PRODUCTION_DB;
  CREATE SCHEMA EDW_PROD_LANDING_SC;
  CREATE SCHEMA EDW_PROD_BRONZE_SC;
  CREATE SCHEMA EDW_PROD_SILVER_SC;
  CREATE SCHEMA EDW_PROD_GOLD_SC;
  CREATE SCHEMA EDW_PROD_PROCESS_SC;

USE DATABASE EDW_DEVELOPMENT_DB;
CREATE DATABASE EDW_DEVELOPMENT_DB;
  CREATE SCHEMA EDW_DEV_LANDING_SC;
  CREATE SCHEMA EDW_DEV_BRONZE_SC;
  CREATE SCHEMA EDW_DEV_SILVER_SC;
  CREATE SCHEMA EDW_DEV_GOLD_SC;
  CREATE SCHEMA EDW_DEV_PROCESS_SC;


USE DATABASE EDW_QUALITY_ANALYSIS_DB;
CREATE DATABASE EDW_QUALITY_ANALYSIS_DB;
  CREATE SCHEMA EDW_QA_LANDING_SC;
  CREATE SCHEMA EDW_QA_BRONZE_SC;
  CREATE SCHEMA EDW_QA_SILVER_SC;
  CREATE SCHEMA EDW_QA_GOLD_SC;
  CREATE SCHEMA EDW_QA_PROCESS_SC;

CREATE OR REPLACE WAREHOUSE EDW_DEV_SMALL_WH
  WAREHOUSE_SIZE = 'SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_QA_SMALL_WH
  WAREHOUSE_SIZE = 'SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_PROD_SMALL_WH
  WAREHOUSE_SIZE = 'SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_PROD_MEDIUM_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_PROD_HEAVYLOAD_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  WAREHOUSE_TYPE = 'STANDARD'
  MIN_CLUSTER_COUNT = 2
  MAX_CLUSTER_COUNT = 5
  SCALING_POLICY = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE ROLE ETL_DEVELOPER_RL;
CREATE ROLE ETL_TESTER_RL;

GRANT USAGE ON DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

-- CREATE / DDL privileges on ALL & FUTURE SCHEMAS
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE SEQUENCE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;

GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;

GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE SEQUENCE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

-- Warehouse usage 
GRANT USAGE ON WAREHOUSE EDW_PROD_SMALL_WH TO ROLE ETL_DEVELOPER_RL;        
GRANT USAGE ON WAREHOUSE EDW_PROD_MEDIUM_WH TO ROLE ETL_DEVELOPER_RL;       
GRANT USAGE ON WAREHOUSE EDW_PROD_HEAVYLOAD_WH TO ROLE ETL_DEVELOPER_RL; 
GRANT USAGE ON WAREHOUSE EDW_DEV_SMALL_WH TO ROLE ETL_DEVELOPER_RL; 

GRANT CREATE SCHEMA ON DATABASE "EDW_DEVELOPMENT_DB" TO ROLE "ETL_DEVELOPER_RL";

CREATE USER AJAYKUMARKARRI
  PASSWORD = 'Temp_Pass#123'
  DEFAULT_ROLE = ETL_DEVELOPER_RL
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER RENUSRIBOTTA
  PASSWORD = 'Temp_Pass#123'
  DEFAULT_ROLE = ETL_DEVELOPER_RL
  MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ETL_DEVELOPER_RL TO USER AJAYKUMARKARRI;
GRANT ROLE ETL_DEVELOPER_RL TO USER RENUSRIBOTTA;


