-- Creating Required DB's, Schema's & Warehouse's.

CREATE DATABASE EDW_PRODUCTION_DB;
  CREATE SCHEMA EDW_PROD_LANDING_SC;
  CREATE SCHEMA EDW_PROD_BRONZE_SC;
  CREATE SCHEMA EDW_PROD_SILVER_SC;
  CREATE SCHEMA EDW_PROD_GOLD_SC;

CREATE DATABASE EDW_DEVELOPMENT_DB;
  CREATE SCHEMA EDW_DEV_LANDING_SC;
  CREATE SCHEMA EDW_DEV_BRONZE_SC;
  CREATE SCHEMA EDW_DEV_SILVER_SC;
  CREATE SCHEMA EDW_DEV_GOLD_SC;

CREATE DATABASE EDW_QUALITY_ANALYSIS_DB;
  CREATE SCHEMA EDW_QA_LANDING_SC;
  CREATE SCHEMA EDW_QA_BRONZE_SC;
  CREATE SCHEMA EDW_QA_SILVER_SC;
  CREATE SCHEMA EDW_QA_GOLD_SC;

CREATE OR REPLACE WAREHOUSE EDW_PROD_SMALL_WH
  WAREHOUSE_SIZE = 'SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_DEV_SMALL_WH
  WAREHOUSE_SIZE = 'SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_QA_SMALL_WH
  WAREHOUSE_SIZE = 'SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_PROD_MEDIUM_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE EDW_PROD_HEAVYLOAD_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  WAREHOUSE_TYPE = 'STANDARD'
  MIN_CLUSTER_COUNT = 2
  MAX_CLUSTER_COUNT = 5
  SCALING_POLICY = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
