CREATE ROLE ETL_DEVELOPER_RL;
CREATE ROLE ETL_TESTER_RL;

GRANT USAGE ON DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

-- CREATE / DDL privileges on ALL & FUTURE SCHEMAS
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE SEQUENCE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON ALL SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;

GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON FUTURE SCHEMAS IN DATABASE EDW_PRODUCTION_DB TO ROLE ETL_DEVELOPER_RL;

GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE SEQUENCE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON ALL SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE VIEW  ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STAGE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE FILE FORMAT ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE PIPE ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE STREAM ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;
GRANT CREATE TASK ON FUTURE SCHEMAS IN DATABASE EDW_DEVELOPMENT_DB TO ROLE ETL_DEVELOPER_RL;

-- Warehouse usage 
GRANT USAGE ON WAREHOUSE EDW_PROD_SMALL_WH TO ROLE ETL_DEVELOPER_RL;        
GRANT USAGE ON WAREHOUSE EDW_PROD_MEDIUM_WH TO ROLE ETL_DEVELOPER_RL;       
GRANT USAGE ON WAREHOUSE EDW_PROD_HEAVYLOAD_WH TO ROLE ETL_DEVELOPER_RL; 
GRANT USAGE ON WAREHOUSE EDW_DEV_SMALL_WH TO ROLE ETL_DEVELOPER_RL; 

GRANT CREATE SCHEMA ON DATABASE "EDW_DEVELOPMENT_DB" TO ROLE "ETL_DEVELOPER_RL";



GRANT ROLE ETL_DEVELOPER_RL TO USER AJAYKUMARKARRI;
GRANT ROLE ETL_DEVELOPER_RL TO USER RENUSRIBOTTA;


