CREATE USER AJAYKUMARKARRI
  PASSWORD = 'Temp_Pass#123'
  DEFAULT_ROLE = ETL_DEVELOPER_RL
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER RENUSRIBOTTA
  PASSWORD = 'Temp_Pass#123'
  DEFAULT_ROLE = ETL_DEVELOPER_RL
  MUST_CHANGE_PASSWORD = TRUE;